### ISSUE TITLE
Was tweet.avsc generated?

### ISSUE THREAD

**Issue by cupdike** [alexhanna/hadoop#1]
I'm curious if tweet.avsc was generated and, if so, using what tools?  
I tried generating something with kite-sdk but it seemed like it couldn't handle the complexity.

**Comment by alexhanna** [comment]
Which files are you referencing?

**Comment by cupdike** [comment]
This one:  https://github.com/alexhanna/hadoop/blob/master/utils/tweet.avsc

**Comment by alexhanna** [comment]
Given that I wrote this code over 5 years ago, I honestly forget.
But apparently you can autogenerate Avro schema with Spark given an example JSON file.

https://stackoverflow.com/questions/24549146/generating-an-avro-schema-from-a-json-document

**Comment by cupdike** [comment]
Yeah, I banged on that approach too.  Dies with an error when trying to save the file--very little to go on from the error.

**Comment by alexhanna** [comment]
Oof. Okay. Sorry, I can't recall how I built the schema. I may have done it manually.
